#!/usr/bin/env node
/**
 * write-env.mjs — .env 파일 생성/업데이트
 *
 * Usage:
 *   node write-env.mjs \
 *     --discord-token TOKEN \
 *     --api-key KEY \
 *     --guild-id GUILD \
 *     --discord-owner ID \
 *     --owner-name NAME
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { homedir } from 'node:os';

const HOME = homedir();
const args = process.argv.slice(2);

function getArg(flag) {
  const idx = args.indexOf(flag);
  return idx !== -1 ? args[idx + 1] : null;
}

const token     = getArg('--discord-token');
const apiKey    = getArg('--api-key');
const guildId   = getArg('--guild-id');
const ownerId   = getArg('--discord-owner');
const ownerName = getArg('--owner-name');

if (!token || !apiKey || !guildId || !ownerId || !ownerName) {
  console.error(JSON.stringify({ error: 'Missing required arguments', args }));
  process.exit(1);
}

const botHome = join(HOME, '.local', 'share', 'jarvis');
const jarvisHome = join(HOME, '.jarvis');

const content = `# Jarvis Infrastructure Environment
# Generated by onboarding skill — $(date)

DISCORD_TOKEN=${token}
ANTHROPIC_API_KEY=${apiKey}

# Discord server
GUILD_ID=${guildId}
OWNER_DISCORD_ID=${ownerId}
OWNER_NAME=${ownerName}

# Discord channels (onboarding 후 채널 추가 시 자동 업데이트)
CHANNEL_IDS=

# Data home
BOT_HOME=${botHome}
`;

// 필요 디렉토리 생성
for (const dir of [
  jarvisHome,
  join(jarvisHome, 'config'),
  botHome,
  join(botHome, 'logs'),
  join(botHome, 'state'),
  join(botHome, 'context'),
  join(botHome, 'inbox'),
  join(botHome, 'results'),
  join(botHome, 'rag'),
  join(botHome, 'data'),
  join(botHome, 'config'),
  join(botHome, 'discord', 'lib'),
]) {
  mkdirSync(dir, { recursive: true });
}

const paths = [
  join(jarvisHome, '.env'),
  join(botHome, '.env'),
];

for (const p of paths) {
  writeFileSync(p, content, { mode: 0o600 });
}

console.log(JSON.stringify({ status: 'ok', paths }));
